#!/usr/bin/python3

import sys

def factorize(num):
    factors = []
    for i in range(2, int(num**0.5) + 1):
        while num % i == 0:
            factors.append(i)
            num //= i
    if num > 1:
        factors.append(num)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    
    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        numbers = file.readlines()
    
    for num in numbers:
        num = int(num)
        factors = factorize(num)
        print(f"{num}={'*'.join(map(str, factors[:2]))}")

if __name__ == "__main__":
    main()

