#!/usr/bin/python3

import sys
import math

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def prime_factors(num):
    factors = []
    for i in range(2, int(math.sqrt(num)) + 1):
        while num % i == 0:
            if is_prime(i):
                factors.append(i)
                num //= i
            else:
                break
    if num > 1 and is_prime(num):
        factors.append(num)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)
    
    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        number = int(file.readline())
    
    factors = prime_factors(number)
    print(f"{number}={'*'.join(map(str, factors))}")

if __name__ == "__main__":
    main()

